name: Main
on: 
  - push
  - pull_request
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Cargo check
        run: cargo check
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install rust target
        run: rustup target add wasm32-unknown-unknown
      - uses: baptiste0928/cargo-install@v1
        with:
          crate: trunk
      - name: Install
        run: npm i
      - name: Build
        run: trunk build
      - name: Test
        run: |
          trunk serve &
          npx cypress run
  test_deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.ref_name == 'main'
    needs:
      - test
      - check
    steps:
      - uses: actions/checkout@v3
      - uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          dry-run: true
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref_name == 'main'
    needs: 
      - test
      - check
      - test_deploy
    steps:
      - uses: actions/checkout@v3
      - uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}