name: Main
on: 
  - push
  - pull_request
jobs:
  check:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Cargo check
        run: cargo check